# Generated by Django 4.0.4 on 2022-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_n', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('total_p', models.IntegerField()),
                ('shipping_a', models.CharField(max_length=100)),
                ('client_n', models.CharField(max_length=100)),
            ],
        ),
    ]
