# Generated by Django 4.0.4 on 2022-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sells'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='client_p',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
