# Generated by Django 4.0.4 on 2022-05-30 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9}$')]),
        ),
    ]
